/**
 * Static ZIP-prefix to BLS CEX metro area mapping.
 * Uses first 3 digits of ZIP code for lookup efficiency.
 * Covers major US metropolitan areas with BLS Consumer Expenditure Survey data.
 * Unknown ZIPs return "National Average" — consistent with BLS CEX fallback.
 */

const ZIP_PREFIX_TO_METRO: Record<string, string> = {
  // Northeast
  '100': 'New York-Newark-Jersey City, NY-NJ-PA',
  '101': 'New York-Newark-Jersey City, NY-NJ-PA',
  '102': 'New York-Newark-Jersey City, NY-NJ-PA',
  '103': 'New York-Newark-Jersey City, NY-NJ-PA',
  '104': 'New York-Newark-Jersey City, NY-NJ-PA',
  '110': 'New York-Newark-Jersey City, NY-NJ-PA',
  '111': 'New York-Newark-Jersey City, NY-NJ-PA',
  '112': 'New York-Newark-Jersey City, NY-NJ-PA',
  '113': 'New York-Newark-Jersey City, NY-NJ-PA',
  '114': 'New York-Newark-Jersey City, NY-NJ-PA',
  '115': 'New York-Newark-Jersey City, NY-NJ-PA',
  '116': 'New York-Newark-Jersey City, NY-NJ-PA',
  '070': 'New York-Newark-Jersey City, NY-NJ-PA',
  '071': 'New York-Newark-Jersey City, NY-NJ-PA',
  '072': 'New York-Newark-Jersey City, NY-NJ-PA',
  '073': 'New York-Newark-Jersey City, NY-NJ-PA',
  '074': 'New York-Newark-Jersey City, NY-NJ-PA',
  '020': 'Boston-Cambridge-Newton, MA-NH',
  '021': 'Boston-Cambridge-Newton, MA-NH',
  '022': 'Boston-Cambridge-Newton, MA-NH',
  '023': 'Boston-Cambridge-Newton, MA-NH',
  '024': 'Boston-Cambridge-Newton, MA-NH',
  '191': 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
  '192': 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
  '193': 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
  '190': 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD',
  '152': 'Pittsburgh, PA',
  '153': 'Pittsburgh, PA',
  '154': 'Pittsburgh, PA',
  '200': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '201': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '202': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '203': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '204': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '205': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '206': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '207': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '208': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '209': 'Washington-Arlington-Alexandria, DC-VA-MD-WV',
  '210': 'Baltimore-Columbia-Towson, MD',
  '211': 'Baltimore-Columbia-Towson, MD',
  '212': 'Baltimore-Columbia-Towson, MD',
  '214': 'Baltimore-Columbia-Towson, MD',
  // Southeast
  '300': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '301': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '302': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '303': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '304': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '305': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '306': 'Atlanta-Sandy Springs-Alpharetta, GA',
  '331': 'Miami-Fort Lauderdale-Pompano Beach, FL',
  '332': 'Miami-Fort Lauderdale-Pompano Beach, FL',
  '333': 'Miami-Fort Lauderdale-Pompano Beach, FL',
  '334': 'Miami-Fort Lauderdale-Pompano Beach, FL',
  '320': 'Jacksonville, FL',
  '321': 'Jacksonville, FL',
  '322': 'Jacksonville, FL',
  '338': 'Tampa-St. Petersburg-Clearwater, FL',
  '337': 'Tampa-St. Petersburg-Clearwater, FL',
  '326': 'Tampa-St. Petersburg-Clearwater, FL',
  '270': 'Charlotte-Concord-Gastonia, NC-SC',
  '271': 'Charlotte-Concord-Gastonia, NC-SC',
  '272': 'Charlotte-Concord-Gastonia, NC-SC',
  '275': 'Raleigh-Cary, NC',
  '276': 'Raleigh-Cary, NC',
  '277': 'Raleigh-Cary, NC',
  '370': 'Nashville-Davidson-Murfreesboro-Franklin, TN',
  '371': 'Nashville-Davidson-Murfreesboro-Franklin, TN',
  '372': 'Nashville-Davidson-Murfreesboro-Franklin, TN',
  // Midwest
  '606': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '607': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '608': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '609': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '600': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '601': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '602': 'Chicago-Naperville-Elgin, IL-IN-WI',
  '441': 'Cleveland-Elyria, OH',
  '440': 'Cleveland-Elyria, OH',
  '442': 'Cleveland-Elyria, OH',
  '432': 'Columbus, OH',
  '430': 'Columbus, OH',
  '431': 'Columbus, OH',
  '481': 'Detroit-Warren-Dearborn, MI',
  '482': 'Detroit-Warren-Dearborn, MI',
  '483': 'Detroit-Warren-Dearborn, MI',
  '480': 'Detroit-Warren-Dearborn, MI',
  '551': 'Minneapolis-St. Paul-Bloomington, MN-WI',
  '552': 'Minneapolis-St. Paul-Bloomington, MN-WI',
  '553': 'Minneapolis-St. Paul-Bloomington, MN-WI',
  '640': 'Kansas City, MO-KS',
  '641': 'Kansas City, MO-KS',
  '660': 'Kansas City, MO-KS',
  '631': 'St. Louis, MO-IL',
  '630': 'St. Louis, MO-IL',
  '632': 'St. Louis, MO-IL',
  // South Central
  '750': 'Dallas-Fort Worth-Arlington, TX',
  '751': 'Dallas-Fort Worth-Arlington, TX',
  '752': 'Dallas-Fort Worth-Arlington, TX',
  '753': 'Dallas-Fort Worth-Arlington, TX',
  '754': 'Dallas-Fort Worth-Arlington, TX',
  '760': 'Dallas-Fort Worth-Arlington, TX',
  '761': 'Dallas-Fort Worth-Arlington, TX',
  '762': 'Dallas-Fort Worth-Arlington, TX',
  '763': 'Dallas-Fort Worth-Arlington, TX',
  '770': 'Houston-The Woodlands-Sugar Land, TX',
  '771': 'Houston-The Woodlands-Sugar Land, TX',
  '772': 'Houston-The Woodlands-Sugar Land, TX',
  '773': 'Houston-The Woodlands-Sugar Land, TX',
  '774': 'Houston-The Woodlands-Sugar Land, TX',
  '782': 'San Antonio-New Braunfels, TX',
  '783': 'San Antonio-New Braunfels, TX',
  '784': 'San Antonio-New Braunfels, TX',
  '787': 'Austin-Round Rock-Georgetown, TX',
  '786': 'Austin-Round Rock-Georgetown, TX',
  '785': 'Austin-Round Rock-Georgetown, TX',
  '700': 'New Orleans-Metairie, LA',
  '701': 'New Orleans-Metairie, LA',
  '703': 'New Orleans-Metairie, LA',
  // Mountain West
  '800': 'Denver-Aurora-Lakewood, CO',
  '801': 'Denver-Aurora-Lakewood, CO',
  '802': 'Denver-Aurora-Lakewood, CO',
  '803': 'Denver-Aurora-Lakewood, CO',
  '804': 'Denver-Aurora-Lakewood, CO',
  '805': 'Denver-Aurora-Lakewood, CO',
  '840': 'Salt Lake City, UT-ID',
  '841': 'Salt Lake City, UT-ID',
  '842': 'Salt Lake City, UT-ID',
  '843': 'Salt Lake City, UT-ID',
  '844': 'Salt Lake City, UT-ID',
  '850': 'Phoenix-Mesa-Chandler, AZ',
  '851': 'Phoenix-Mesa-Chandler, AZ',
  '852': 'Phoenix-Mesa-Chandler, AZ',
  '853': 'Phoenix-Mesa-Chandler, AZ',
  '854': 'Phoenix-Mesa-Chandler, AZ',
  '855': 'Phoenix-Mesa-Chandler, AZ',
  '856': 'Tucson, AZ',
  '857': 'Tucson, AZ',
  '870': 'Albuquerque, NM',
  '871': 'Albuquerque, NM',
  '872': 'Albuquerque, NM',
  '890': 'Las Vegas-Henderson-Paradise, NV',
  '891': 'Las Vegas-Henderson-Paradise, NV',
  '893': 'Las Vegas-Henderson-Paradise, NV',
  // Pacific
  '900': 'Los Angeles-Long Beach-Anaheim, CA',
  '901': 'Los Angeles-Long Beach-Anaheim, CA',
  '902': 'Los Angeles-Long Beach-Anaheim, CA',
  '903': 'Los Angeles-Long Beach-Anaheim, CA',
  '904': 'Los Angeles-Long Beach-Anaheim, CA',
  '905': 'Los Angeles-Long Beach-Anaheim, CA',
  '906': 'Los Angeles-Long Beach-Anaheim, CA',
  '907': 'Los Angeles-Long Beach-Anaheim, CA',
  '908': 'Los Angeles-Long Beach-Anaheim, CA',
  '910': 'Los Angeles-Long Beach-Anaheim, CA',
  '911': 'Los Angeles-Long Beach-Anaheim, CA',
  '912': 'Los Angeles-Long Beach-Anaheim, CA',
  '913': 'Los Angeles-Long Beach-Anaheim, CA',
  '914': 'Los Angeles-Long Beach-Anaheim, CA',
  '915': 'Los Angeles-Long Beach-Anaheim, CA',
  '916': 'Los Angeles-Long Beach-Anaheim, CA',
  '917': 'Los Angeles-Long Beach-Anaheim, CA',
  '918': 'Los Angeles-Long Beach-Anaheim, CA',
  '919': 'San Diego-Chula Vista-Carlsbad, CA',
  '920': 'San Diego-Chula Vista-Carlsbad, CA',
  '921': 'San Diego-Chula Vista-Carlsbad, CA',
  '922': 'San Diego-Chula Vista-Carlsbad, CA',
  '923': 'San Diego-Chula Vista-Carlsbad, CA',
  '924': 'San Diego-Chula Vista-Carlsbad, CA',
  '925': 'San Diego-Chula Vista-Carlsbad, CA',
  '926': 'Riverside-San Bernardino-Ontario, CA',
  '927': 'Riverside-San Bernardino-Ontario, CA',
  '928': 'Riverside-San Bernardino-Ontario, CA',
  '930': 'Oxnard-Thousand Oaks-Ventura, CA',
  '931': 'Oxnard-Thousand Oaks-Ventura, CA',
  '932': 'Bakersfield, CA',
  '933': 'Bakersfield, CA',
  '934': 'Santa Barbara-Santa Maria-Goleta, CA',
  '935': 'Santa Barbara-Santa Maria-Goleta, CA',
  '936': 'Fresno, CA',
  '937': 'Fresno, CA',
  '938': 'Fresno, CA',
  '939': 'Sacramento-Roseville-Folsom, CA',
  '940': 'San Francisco-Oakland-Berkeley, CA',
  '941': 'San Francisco-Oakland-Berkeley, CA',
  '942': 'San Francisco-Oakland-Berkeley, CA',
  '943': 'San Francisco-Oakland-Berkeley, CA',
  '944': 'San Francisco-Oakland-Berkeley, CA',
  '945': 'San Francisco-Oakland-Berkeley, CA',
  '946': 'San Francisco-Oakland-Berkeley, CA',
  '947': 'San Francisco-Oakland-Berkeley, CA',
  '948': 'San Francisco-Oakland-Berkeley, CA',
  '949': 'San Francisco-Oakland-Berkeley, CA',
  '950': 'San Jose-Sunnyvale-Santa Clara, CA',
  '951': 'San Jose-Sunnyvale-Santa Clara, CA',
  '952': 'San Jose-Sunnyvale-Santa Clara, CA',
  '953': 'San Jose-Sunnyvale-Santa Clara, CA',
  '954': 'San Jose-Sunnyvale-Santa Clara, CA',
  '955': 'Sacramento-Roseville-Folsom, CA',
  '956': 'Sacramento-Roseville-Folsom, CA',
  '957': 'Sacramento-Roseville-Folsom, CA',
  '958': 'Sacramento-Roseville-Folsom, CA',
  '960': 'Redding, CA',
  '961': 'Redding, CA',
  '970': 'Portland-Vancouver-Hillsboro, OR-WA',
  '971': 'Portland-Vancouver-Hillsboro, OR-WA',
  '972': 'Portland-Vancouver-Hillsboro, OR-WA',
  '973': 'Portland-Vancouver-Hillsboro, OR-WA',
  '974': 'Portland-Vancouver-Hillsboro, OR-WA',
  '975': 'Portland-Vancouver-Hillsboro, OR-WA',
  '980': 'Seattle-Tacoma-Bellevue, WA',
  '981': 'Seattle-Tacoma-Bellevue, WA',
  '982': 'Seattle-Tacoma-Bellevue, WA',
  '983': 'Seattle-Tacoma-Bellevue, WA',
  '984': 'Seattle-Tacoma-Bellevue, WA',
  '985': 'Seattle-Tacoma-Bellevue, WA',
  '986': 'Seattle-Tacoma-Bellevue, WA',
  '996': 'Anchorage, AK',
  '995': 'Anchorage, AK',
  '967': 'Urban Honolulu, HI',
  '968': 'Urban Honolulu, HI',
}

/**
 * Look up BLS CEX metro area name for a 5-digit ZIP code.
 * Uses the first 3 digits as a prefix key.
 * Returns "National Average" for unknown ZIPs (matches BLS CEX fallback).
 */
export function zipToMetro(zip: string): string {
  if (!zip || zip.length < 3) return 'National Average'
  const prefix = zip.slice(0, 3)
  return ZIP_PREFIX_TO_METRO[prefix] ?? 'National Average'
}

export { ZIP_PREFIX_TO_METRO as ZIP_TO_METRO }
