// Auto-generated by `supabase gen types typescript --project-id <id>`
// This is a placeholder until the schema is deployed and types are generated.
// Replace this file by running: supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/database.ts

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
